# This YAML file defines the relationship and deployment ordering of your environments.

# The name of the pipeline
name: pipeline-ecs-fargate-pilot-archer-nyan-cat

# The version of the schema used in this template
version: 1

# This section defines the source artifacts.
source:
  # The name of the provider that is used to store the source artifacts.
  provider: GitHub
  # Additional properties that further specifies the exact location
  # the artifacts should be sourced from. For example, the GitHub provider
  # has the following properties: repository, branch.
  properties:
    access_token_secret: github-token-ecs-fargate-pilot-archer-nyan-cat
    branch: master
    repository: jstu994/archer-nyan-cat

# The deployment section defines the order the pipeline will deploy
# to your environments.
stages:
  - # The name of the environment to deploy to.
    name: test
    apps:
      ecs-fargate-pilot:
        integrationTestBuildspec: buildspec_integ.yml